version: '3'
services:
  aws-otel-collector:
    image: amazon/aws-otel-collector:latest
    volumes:
      - ~/.aws:/root/.aws
    ports:
      - '4317:4317' # OTLP receiver
    environment:
      - AWS_REGION=ap-northeast-2
    command: ['--config=/etc/ecs/ecs-cloudwatch-xray.yaml']
  chatbot:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    volumes:
      - ./.cache:/app/.cache
    ports:
      - 8080:8080
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aws-otel-collector:4317
      - OTEL_SERVICE_NAME=chatbot
