version: '3'
services:
  polyglot:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./.cache:/app/.cache
