[app]
ns="ChatbotDemo"
stage="Dev"

[aws]
account="" # e.g. 123456789012
region="ap-northeast-2"

[vpc]
id="" # e.g. vpc-xxx

[service]
[service.common]
port=8080

[service.front]
name="front"
repositoryName="front"
tag="85678f55ea"
[service.chatbot]
name="chatbot"
repositoryName="chatbot"
tag="343fe0be2a"