version: '3'

dotenv: [.env]

tasks:
  ecr-login:
    vars:
      REGION: ap-northeast-2
    cmds:
      - aws ecr get-login-password --region {{.REGION}} | docker login --username AWS --password-stdin "$(aws sts get-caller-identity --query Account --output text).dkr.ecr.{{.REGION}}.amazonaws.com"

  build-app-image:
    vars:
      BUILD_TAG:
        sh: git rev-parse --short=10 HEAD
    cmds:
      - docker build -t {{.APP_NAME}}:{{.BUILD_TAG}} .

  push-image:
    vars:
      REGION: ap-northeast-2
      BUILD_TAG:
        sh: git rev-parse --short=10 HEAD
    cmds:
      - docker tag {{.APP_NAME}}:{{.BUILD_TAG}} $(aws sts get-caller-identity --query Account --output text).dkr.ecr.{{.REGION}}.amazonaws.com/{{.APP_NAME}}:{{.BUILD_TAG}}
      - docker push $(aws sts get-caller-identity --query Account --output text).dkr.ecr.{{.REGION}}.amazonaws.com/{{.APP_NAME}}:{{.BUILD_TAG}}

  build-all:
    cmds:
      - task: build-app-image
        vars: { APP_NAME: 'front' }

  push-all:
    deps: [ecr-login]
    cmds:
      - task: push-image
        vars: { APP_NAME: 'front' }

  create-repo:
    vars:
      REPOSITORIES: |
        front

    cmds:
      - |
        ARR=(`echo "{{.REPOSITORIES}}" | tr '\n' ' '`)
        for REPO in ${ARR[@]}
        do
          aws ecr create-repository --repository-name ${REPO} {{.CLI_ARGS}}
        done
